### ISSUE TITLE
Can't set the workflow up.

### ISSUE THREAD

**Issue by politicus** [dberube/trello-alfred#2]
When I type trello for the first time I get "Add: card to Trello". I can't authorize Alfred -> can't use the workflow. No error in Alfred console log.

**Comment by fnurl** [comment]
I had the same issue. @dberube you left your config.ini in the .alfredworkflow

@politicus You have to go to the workflow directory and remove the file config.ini

**Comment by cliffordfajardo** [comment]
I'm having the same issue as @politicus @fnurl

**Comment by iansoper** [comment]
I noticed this too. If you downloaded from Packal the issue is the config.ini is already included in that download and it setup for the author's account.

**Comment by politicus** [comment]
@iansoper Thank you! I could make the workflow work after deleting the config.ini file and following the set up of the Readme.md file.

**Comment by dberube** [comment]
My bad -- didn't realize this was still in there. Removed with v0.9.1 and updated Packal
