### ISSUE TITLE
Trello:auth command not functioning

### ISSUE THREAD

**Issue by robynlarsen** [dberube/trello-alfred#5]
Not sure which step I missed but after downloading I have been unable to access the `trello:auth` command. `trello:setup` pulls up the paste in your auth token but I'm not sure how to access this. Any thoughts would be helpful.

**Comment by politicus** [comment]
Just like robynlarsen, I  can't make the "trello:auth" command functioning.

I wanted to update my workflow to the latest version. So I deleted the one I previously used, installed the new one. The first time I typed "trello" the first result I got in Alfred'd bar was "Add card : to Trello". 

 When I tried to add a card, the workflow notified me I added a card in Incoming (a list I do not have in my Trello). I thought there should be a problem with the API key.

So, I decided to revoke the API access to the workflow. Tried "trello:auth" but didn't work. 

Another trello Alfred workflow, another [problem with authorization](http://www.alfredforum.com/topic/1132-create-card-in-trello/?p=35284)

**Comment by robynlarsen** [comment]
@politicus I ended up using the other Trello workflow system. 

Followed these instructions:

http://www.alfredforum.com/topic/5195-understanding-how-to-add-trello-workflow/

With this version of the build: 
https://dl.dropbox.com/s/bb86royejj6r7o7/index.html

Feel free to shoot me any questions if you run into problems.

**Comment by politicus** [comment]
@robynlarsen Awesome! Thank you very much! 
I think I already had tried this workflow but with no luck.

**Comment by robynlarsen** [comment]
Be sure you're using the "jello" command for setup. The confusing part is you need to open the script file in Alfred to enter your token and default board information.

R

Sent from the virtual office

Robyn Larsen
Front-End Web Developer
R&Co robynlarsen.ca 
Tweet me @robyn_larsen

---

**Comment by politicus** [comment]
I use the jello command and filled the script with my credential. And it worked BUT: after spending 30 minutes trying to add cards to trello I decided to give up on using Trello+Alfred: the command "trello Name of the card; description; label; ..." is not reliable in the sense that writing the README trello command worked. While my exact trelllo command with only one change (the card name I wanted to) led to an error. I've tried at the leat 20 times to add card. Goodbye Trello+Alfred!

**Comment by purp** [comment]
Hi, all.

For me, this was related to a [couple of hard-coded paths](purp/trello-alfred@c1db5107abaf11fc0f4f67eeb17528066a4ba4ab) in the workflow that didn't play well with Alfred 3 for some reason. I've got [an alpha build of the workflow here](https://github.com/purp/trello-alfred/raw/master/trello.alfredworkflow) where this is fixed and would welcome comments and issues [in my fork of this repo](https://github.com/purp/trello-alfred/issues).

I'm hoping @dberube will have a moment sometime soonish to help pull these merges in; until then, I'm happy to help support this workflow.

Cheers!

--j
